# frontend/netlify.toml
[build]
  base    = "frontend"
  command = "vite build"
  publish = "dist"

# Fixes the 'application/octet-stream' MIME Type error
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Fixes the 'Uncaught SyntaxError: Unexpected token <' error
# by preventing assets from being redirected to index.html
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# React Router SPA Fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200